#!/bin/bash
set -e

echo "Cloning target projects..."

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
targets=$(cat "$dir/targets")

for target in $targets; do
  [[ "$target" =~ ([^\|]*)\|(.*) ]]
  repo="${BASH_REMATCH[1]}"
  branch="${BASH_REMATCH[2]}"

  [[ "$repo" =~ [^/]*/(.*) ]]
  name="${BASH_REMATCH[1]}"

  echo ""
  git clone "$repo" "projects/$name"
  cd "projects/$name"
  git checkout "$branch"
  cd ../..
done
