#!/bin/bash
set -e

echo "Running git for target projects..."

for project in ./projects/*; do
  [[ "$project" =~ [^/]*/(.*) ]]
  name="${BASH_REMATCH[1]}"

  echo ""
  echo "$name:"
  
  cd "$project"
  git "$@"
  cd ../..
done
